### ISSUE TITLE
To Do [checklist]

### ISSUE THREAD

**Issue by sabahzero** [sabahzero/WRP#8]
- [ ] Integrate notes from May 28 Lab Meeting presentation 
- [ ] Integrate Google Doc Research Notes
- [ ] Update README 
- [ ] Clean-up Issues
